### ISSUE TITLE
[BUG]: Missing argument in animateLevyConstruction

### ISSUE THREAD

**Issue by johnny-godoy** [pabloisaacalexz/Visualizing-math#1]
(If you prefer for me to write in English for this repository tell me, but I'll go for Spanish now)

¡Hola Pablo!

Está bueno el repo! Estaba  jugando un poco con las visualizaciones, y quería reportar un bug. La función `animateLevyConstruction` utiliza una variable `n` sin antes definirla. Esto no se nota al correrlo desde Jupyter porque defines `n=11`, pero si hubieras utilizado otro nombre de variable:

```
k = 11
t, F, B = LevyConstructionBM(k)
```

Entonces al correr  `animateLevyConstruction` se cae por `NameError: name 'n' is not defined`. Una solución fácil de implementar es agregar `n` como argumento a la función, pero no sé si es la que tú prefieres.

PD: Estaba haciendo mejoras de eficiencia al código (Con cambios simples se puede hacer un boost de x28 a `LevyConstructionBM`). Ví que estabas abierto a aportes: ¿Prefieres que te haga un pull request para esto?

**Comment by pabloisaacalexz** [comment]
Hola Johnny!

Muchas gracias por tus comentarios y tus observaciones :) en virtud del
tiempo, estaría encantado de que hagas un pull request para la velocidad de
la función.

Decir que ambos .ipynb del repo los usé para un video de divulgación sobre
el movimiento browniano y sacando las animaciones debo haber cambiado esa
cosa ínfima sobre el n.

Quedo atento entonces!
Saludos
Pablo

**Comment by johnny-godoy** [comment]
Resuelto en https://github.com/pabloisaacalexz/Visualizing-math/pull/2
